server=http://localhost:4120
apiVersion=/api/v1/

admin.username=admin
admin.password=admin

baseUrl = http://localhost:3000
browser = chrome
browserSize = 1920x1080

# Database configuration
db.url=jdbc:postgresql://localhost:5440/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers

# Fraud service configuration (for testing with WireMock)
fraud.service.url=http://localhost:8090
