services:
  backend:
    image: nobugsme/nbank:with_fraud_check_with_transfer_fix
    ports:
      - "4120:4111"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5440/nbank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - FRAUD_DETECTION_SERVICE_URL=http://host.docker.internal:8090
